version: "3"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    volumes:
      - ../app:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
